services:
  web_server:
    build: .
    ports:
      - ${WEB_SERVER_PORT}:3000
    depends_on:
      - database
      - redis
    container_name: 2dam-inventory-webserver
    working_dir: /web
    command: pm2-runtime start pm2.json
    volumes:
      - ./2dam_inventory:/web
  database:
    image: yobasystems/alpine-mariadb:10.11.8
    container_name: 2dam-inventory-db
    #restart: always
    environment:
     - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
     - TZ=UTC
    #volumes:
    # - ./data/db/mysql:/var/lib/mysql
    # - ./mysql.cnf:/etc/mysql/my.cnf
  redis: 
    image: 'redis'
    container_name: 2dam-inventory-redis
